"""empty message

Revision ID: 387aa9637448
Revises: 6e07c0fb53fe
Create Date: 2021-11-27 10:09:52.595132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '387aa9637448'
down_revision = '6e07c0fb53fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('data', sa.DATETIME(), nullable=False))
    op.alter_column('pedidos', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('pedidos', 'status',
               existing_type=sa.CHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'status',
               existing_type=sa.CHAR(length=1),
               nullable=True)
    op.alter_column('pedidos', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('pedidos', 'data')
    # ### end Alembic commands ###
