"""empty message

Revision ID: 6e07c0fb53fe
Revises: 7b09727e43b4
Create Date: 2021-11-20 20:16:40.818620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e07c0fb53fe'
down_revision = '7b09727e43b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardapio', sa.Column('imagem', sa.Text(), nullable=True))
    op.add_column('cardapio', sa.Column('mimetype', sa.Text(), nullable=True))
    op.alter_column('cardapio', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('enderecos', 'tipo_endereco',
               existing_type=sa.CHAR(length=1),
               nullable=False)
    op.alter_column('fornecedores', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('insumos', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('insumos_nome_key', 'insumos', type_='unique')
    op.alter_column('pedidos', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('pedidos', 'status_do_pedido')
    op.add_column('preco_insumo', sa.Column('valor', sa.Float(), nullable=False))
    op.drop_column('preco_insumo', 'preco')
    op.alter_column('receitas', 'id_insumo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receitas', 'id_insumo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('preco_insumo', sa.Column('preco', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('preco_insumo', 'valor')
    op.add_column('pedidos', sa.Column('status_do_pedido', sa.CHAR(length=1), autoincrement=False, nullable=False))
    op.alter_column('pedidos', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint('insumos_nome_key', 'insumos', ['nome'])
    op.alter_column('insumos', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fornecedores', 'cnpj',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fornecedores', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('enderecos', 'tipo_endereco',
               existing_type=sa.CHAR(length=1),
               nullable=True)
    op.alter_column('cardapio', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('cardapio', 'mimetype')
    op.drop_column('cardapio', 'imagem')
    # ### end Alembic commands ###
