"""empty message

Revision ID: 7b09727e43b4
Revises: 
Create Date: 2021-11-20 19:49:22.484941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b09727e43b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preco_insumo', sa.Column('valor', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preco_insumo', 'valor')
    # ### end Alembic commands ###
